services:
  - type: web
    name: automated-student-attendance-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd frontend && npm ci && npm run build
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
